---
title: "About me"
---

My research interests concern the intersection of number theory with low-dimensional topology. In particular, I am interested in how and why objects like quantum modular forms and mock modular forms arise in the study of series invariants of 3- and 4-manifolds, which often arise out of categorification/decategorification programs. These questions also make contact with mathematical physics, as many such invariants arise from nonperturbative quantum field theory. 

I am currently a postdoctoral scholar at Vanderbilt University with [Larry Rolen](https://math.vanderbilt.edu/rolenl/) serving as my mentor. 

In Spring 2024, I recieved my Ph.D. at the University of Virginia under my advisor [Ken Ono](https://uva.theopenscholar.com/ken-ono).

In 2020, I graduated from the University of California, Berkeley with a B.A. in Pure Mathematics and a Minor in Gender & Women's Studies. 

I was born in Albany, New York and raised in Denver Colorado. I enjoy urban cycling on my e-bike, reading sci-fi/fantasy/weird fiction, and cooking. 
