---
title: "Publications"
---

1. Liles, L. and McSpirit, E. *[Infinite Families of Quantum Modular 3-manifold Invariants.](https://arxiv.org/abs/2306.14765)* Submitted for Publication. 

2. McSpirit, E. and Ono, K. *[Hypergeometry and the AGM over Finite Fields.](https://arxiv.org/abs/2302.10387)* Contemporary Mathematics, American Mathematical Society. Accepted for publication. 

3. McSpirit, E. *Swinnerton-Dyer and the Ramanujan Congruences for τ(n).* Ramanujan Handbook by Springer. Accepted for publication. 

4. McSpirit, E. *K3 Surfaces and Ramanujan’s Sum of Two Cubes.* Ramanujan Handbook by Springer. Accepted for publication.

5. McSpirit, E. and Ono, K. *[Zeros in the Character Tables of Symmetric Groups with an ℓ-Core Index.](https://www.cambridge.org/core/journals/canadian-mathematical-bulletin/article/zeros-in-the-character-tables-of-symmetric-groups-with-an-ell-core-index/3E5750E7531B430764211FCD332CD7E7)* Canadian Mathematical Bulletin, 66(2), 467-476.

6. McSpirit, E. and Scheckelhoff, K. *[On the Number of 2-Hooks and 3-Hooks of Integer Partitions.](https://www.cambridge.org/core/journals/bulletin-of-the-australian-mathematical-society/article/on-the-number-of-2hooks-and-3hooks-of-integer-partitions/643A8020D3571F35148FEF7896B4DE40)* Bulletin of the Australian Mathematical Society (2022): 1-8.

7. Lin, A. McSpirit, E. and Vishnu, A. *[Algebraic Relations Between Partition Functions and the j-Function.](https://link.springer.com/article/10.1007/s40993-019-0177-7)* Research in
Number Theory **6, 2** (2020).  arXiv:[1907.07763](https://arxiv.org/abs/1907.07763)

**Collaborators**

* [Liles, Louisa](https://sites.google.com/view/louisalilesdoesmath)

* [Lin, Alice](https://www.math.harvard.edu/people/lin-alice/)

* [Ono, Ken](https://uva.theopenscholar.com/ken-ono)

* [Scheckelhoff, Kristen](https://mathstats.uncg.edu/people/directory/kristen-scheckelhoff/)

* [Vishnu, Adit](https://aditvishnu.github.io)
