---
title: "Talks"
---

### Past 

* Joint Meetings of AMS/NZMS/AustMS, Special Session on Special Functions, $q$-Series and Beyond, Keynote Speaker -- December 2024

* Algebra and Number Theory Seminar, Oregon State University -- November 2024

* Number Theory Seminar, Vanderbilt University -- November 2024

* AMS Special Session on Elementary Number Theory and Elliptic Curves, Howard University -- April 2024
 
* Algebra, Geometry, and Number Theory Seminar, University of South Carolina -- March 2024
 
* Algebra and Number Theory Seminar, Louisiana State University -- February 2024
 
* The Web of Modularity, Tulane University -- February 2024
 
* Algebra Seminar, Virginia Tech -- February 2024
 
* Graduate Student Seminar, University of Virginia -- January 2024
 
* JMM AMS Special Session on Mock modular forms, physics, and applications -- January 2024
 
* JMM AMS Special Session on Partition Theory and q-Series -- January 2024
 
* Vanderbilt University Number Theory Seminar -- October 2023
 
* AMS Special Session on Number Theory and Friends, University of South Alabama -- October 2023
  
* Ramanujan–Serre Seminar, University of Virginia -- September 2023
 
* 35th Automorphic Forms Workshop -- May 2023
 
* AMS Special Session on Hypergeometric functions, q-series and generalizations, Virtual -- April 2023
 
* Texas Number Theory and Combinatorics Seminar -- January 2023
 
* Graduate Student Seminar, University of Virginia -- August 2022

* JMM AMS Special Session on Modular Forms and Combinatorics -- January 2022
  
## Additional Conference and Workshop Participation

* Merging Categorification, Gauge Theory, and Physics, Simons Collaboration -- September 2023

* Learning Workshop on BPS States and 3-Manifolds, International Center for Theoretical Physics -- February 2023

* PCMI on Number Theory Informed by Computation -- Summer 2022

* 100 Years of Mock Theta Functions, Vanderbilt University -- May 2022

* Joint Mathematics Meetings, Denver -- January 2020

